[project]
name = "stamp-signature-segregate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ravixpanchal", email = "ravi.panchal.kaithi@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
stamp-signature-segregate = "stamp_signature_segregate:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
